export enum Page {
    MAIN_PAGE,
    STUDENT_SUPERVISOR_ADD_DELEGATEE,
    STUDENT_SUPERVISOR_ATTENUATED,
    DOCTOR_NURSE,
    PROTOCOL_STUDENT_SUPEVISOR,
    PROTOCOL_DOCTOR_NURSE,
    PROTOCOL_EMPLOYEE,
    ED25519,
    SECP256k1
}